services:
  node-red:
    image: nodered/node-red:latest-18-minimal
    container_name: node-red
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "1880:1880"
    networks:
      - iot
    volumes:
      - ./settings.js:/data/settings.js
      - node-red-data:/data

  mosquitto:
    image: eclipse-mosquitto:2-openssl
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - iot
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto:/mosquitto

volumes:
  node-red-data:
  mosquitto:

networks:
  iot:
