services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

  node-red:
    image: nodered/node-red:latest-18-minimal
    container_name: node-red
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./settings.js:/data/settings.js
      - node-red-data:/data

  mosquitto:
    image: eclipse-mosquitto:2-openssl
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto:/mosquitto

volumes:
  caddy-data:
  caddy-config:
  node-red-data:
  mosquitto:

networks:
  default:
    external: true
    name: caddy
 
